<?php
// conflict-list.php - Demonstrates handling a 409 Conflict response during a save operation.

### ⚠️ STEP 1: DEFINE YOUR CONFIGURATION ⚠️

// The Access Token obtained from the server-side OAuth 2.0 exchange.
$ACCESS_TOKEN = 'YOUR_VALID_ACCESS_TOKEN_HERE';

// The ID of the existing snapshot you were attempting to update.
$SNAPSHOT_ID = 'SNAPSHOT_ID_BEING_UPDATED'; 

// Data you were trying to save (this is the "current" save data)
$current_game_data = [
    'player_level' => 50,
    'player_xp'    => 1000,
    'device'       => 'Server Save Attempt',
];
$current_game_data_json = json_encode($current_game_data);

// The PATCH endpoint URL
$api_url = "https://games.googleapis.com/games/v1/snapshots/{$SNAPSHOT_ID}";

// Metadata for the attempted save
$metadata_payload = [
    'description'    => 'Attempted save with new progress.',
    'durationMillis' => 1500000,
];

// Full request payload
$full_payload = [
    'snapshot'         => $metadata_payload,
    'snapshotContents' => base64_encode($current_game_data_json), 
];
$json_payload = json_encode($full_payload);


### STEP 2: EXECUTE THE cURL SAVE REQUEST

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $api_url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PATCH'); 
curl_setopt($ch, CURLOPT_POSTFIELDS, $json_payload);

$headers = [
    "Authorization: Bearer $ACCESS_TOKEN",
    "Content-Type: application/json",
    "Content-Length: " . strlen($json_payload)
];
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$response = curl_exec($ch);
$http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);

if (curl_errno($ch)) {
    echo 'cURL Error: ' . curl_error($ch);
    curl_close($ch);
    exit;
}
curl_close($ch);

### STEP 3: PROCESS THE RESPONSE AND CHECK FOR CONFLICT (HTTP 409)

$result = json_decode($response, true);

if ($http_code === 200) {
    // Successful Save - No Conflict
    echo "✅ Save Successful (HTTP 200). No conflicts found.\n";
    echo "Snapshot ID: {$SNAPSHOT_ID} updated.\n";
    
} elseif ($http_code === 409) {
    // ⚠️ CONFLICT DETECTED ⚠️
    echo "❌ Save Conflict Detected (HTTP 409). Need to display options to player.\n\n";
    
    // Check if the expected conflict fields are present
    if (!isset($result['conflict']) || !isset($result['conflict']['conflictingSnapshots'])) {
        echo "Error: Conflict response format is unexpected.\n";
        print_r($result);
        exit;
    }

    $conflict_id = $result['conflict']['conflictId'];
    $conflicting_snapshots = $result['conflict']['conflictingSnapshots'];

    echo "--- Conflict ID: **{$conflict_id}** ---\n\n";
    
    // The first conflicting snapshot is usually the most relevant server version.
    // The player's data is the data that caused the conflict (the one you attempted to save).
    
    // 1. Display the CURRENT (Unsaved) data the player was using
    echo "## 💾 Option 1: Your Current Device's Save (Attempted Save)\n";
    echo "This data was just generated by the player's device/server.\n";
    echo "  Level: **{$current_game_data['player_level']}**\n";
    echo "  XP: **{$current_game_data['player_xp']}**\n";
    echo "  Source: {$current_game_data['device']}\n";
    echo "--------------------------\n\n";

    // 2. Display the CONFLICTING (Server) data(s)
    echo "## ☁️ Option 2: Conflicting Save(s) Found on Server\n";
    
    $counter = 1;
    foreach ($conflicting_snapshots as $snapshot) {
        $counter++;
        
        // The actual game data is base64 encoded in snapshotContents
        $conflicting_data_json = base64_decode($snapshot['snapshotContents']);
        $conflicting_data = json_decode($conflicting_data_json, true);

        // Safely extract level and XP
        $level = $conflicting_data['player_level'] ?? 'N/A';
        $xp = $conflicting_data['player_xp'] ?? 'N/A';
        
        echo "### Option {$counter}: **{$snapshot['fileName']}**\n";
        echo "  Last Modified: " . date('Y-m-d H:i:s', $snapshot['lastModifiedMillis'] / 1000) . "\n";
        echo "  Description: " . $snapshot['description'] . "\n";
        echo "  Level: **{$level}**\n";
        echo "  XP: **{$xp}**\n";
        echo "  Conflicting ID: {$snapshot['id']}\n";
        echo "--------------------------\n";
    }
    
    echo "\n\n**NEXT STEP:** Send the `conflictId` ({$conflict_id}) and the player's choice (e.g., the ID of the chosen snapshot) back to the server to perform a **Conflict Resolution** save.\n";

} else {
    // Other Errors (e.g., 401 Unauthorized, 404 Not Found)
    echo "❌ An API error occurred (HTTP $http_code).\n\n";
    print_r($result);
}
?>
